### ISSUE TITLE
With empty database, IndexError happens

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#103]
![image](https://user-images.githubusercontent.com/2399010/115235553-f162f680-a137-11eb-8a7e-1a7836c445c2.png)

**Comment by kgashok** [comment]
`r[0]` indicates that it expects at least one inbox. 

![image](https://user-images.githubusercontent.com/2399010/115235981-6f270200-a138-11eb-8a5d-a9986425a238.png)

**Comment by Pavithratrdev** [comment]
Two Scenarios for this issue:
1. Table does not exist - Error will occur (we can ignore it)
2. Table exist and data is empty - We need to fix it
