### ISSUE TITLE
HTTPS certificate issues

### ISSUE THREAD

**Issue by angristan** [BlitzKraft/saythanks.io#105]
I was having issues connecting to saythanks.io with a Rust program, and it turns out the server return an incomplete certificate chain: https://www.ssllabs.com/ssltest/analyze.html?d=saythanks.io

Also, the HTTPS config looks pretty outdated.

Would it be possible to fix it please ? 🙏

**Comment by kgashok** [comment]
@angristan overall rating of "B" is shown. 

![image](https://user-images.githubusercontent.com/2399010/129419873-9a983de8-1540-4eae-b6b6-953eebe8a031.png)

**Comment by kgashok** [comment]
and now...

![image](https://user-images.githubusercontent.com/2399010/129438298-963fb5ee-2ebf-4aaa-9c8e-7566a5349899.png)

**Comment by angristan** [comment]
thanks 🎉
