### ISSUE TITLE
QR Code for saythanks.io URL 

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#109]
![image](https://user-images.githubusercontent.com/2399010/141391768-cd8c2121-95ba-4e75-8d19-d3e36a795daf.png)

In addition to the options of buttons and URL, it would be good to have a QR code for the link as well, similar to something like below: 

 
![thankkg](https://user-images.githubusercontent.com/2399010/141391435-49269fbc-00e2-4e75-b47f-f1d50fe1c6d5.png)

**Comment by DeepakChakravarthy** [comment]
Sir It is a Good Idea to have a QR Code for the Profile-Accounts 
I Would Like to Suggest  PyPI for QR Code Generation [https://pypi.org/project/Flask-QRcode/](url)
There is Clear Documentation for the Pip [https://marcoagner.github.io/Flask-QRcode/#](url)

**Comment by kgashok** [comment]
@DeepakChakravarthy Now, since you think it is a good idea, why don't you implement it yourself?
