### ISSUE TITLE
Broken link to installation markdown file 

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#112]
### Broken Markdown link 

In the [README.md](/home/kgashok/saythanks.io/docs/README.md) file, the "markdown file" link is broken. 

![image](https://user-images.githubusercontent.com/2399010/145583216-ce0c0dec-e635-47f4-ab03-22841d16dfca.png)

**Comment by ashutosh-mishra4** [comment]
Hey @kgashok Please assign this issue to me.
