### ISSUE TITLE
Improve the DEVELOPMENT markdown file

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#114]
The `DEVELOPMENT.md` needs to become more comprehensive. Until then, refer to /docs folder for more details on setting up a development environment.

**Comment by Deepthi-Deepu** [comment]
Sir, I will work on this..

**Comment by Pavithratrdev** [comment]
Sir, I will work on this

**Comment by kgashok** [comment]
@Pavithratrdev , 

See https://github.com/kgashok/memcode/blob/master/Readme.md#initial-setup-for-development for further ideas on how to improve this document.
