### ISSUE TITLE
Refactor the code to use records github repo

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#116]
Use case for ```"SQL for Humans"``` - refactor the SQL code that interacts with the database to use https://github.com/kennethreitz/records. 

![image](https://user-images.githubusercontent.com/2399010/145591675-47708d30-d65c-47fb-80dc-683e6a6bb4bd.png)

**Comment by Pavithratrdev** [comment]
Refactoring involves changing the code so that it is better written or in a position to be made better later on. It is best to constantly make small improvements over time.

**Comment by Pavithratrdev** [comment]
Refactoring is already implemented.
