### ISSUE TITLE
Add a link to create a "New Issue"  on the github project repo

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#118]
By way of providing feedback on the project, a link can be made available at the footer of every page

> ![image](https://user-images.githubusercontent.com/2399010/145620445-6afbfd9f-69f8-4e67-8894-eb5ae579380c.png)

This will encourage users/reviewers to make suggestions for improving the project. Create an additional line with a link to the "New Issue" dialog, exactly as shown below:

![image](https://user-images.githubusercontent.com/2399010/145622803-b96d1b37-9523-4f80-8182-8ed8ac5dab1c.png)

Once the link is clicked, the "New Issue" dialog (shown below) should open up in a new tab/window, as shown below: 

> ![image](https://user-images.githubusercontent.com/2399010/145620741-c7083eb1-9c9c-4fc2-9ed6-80155deed3b1.png)

**Comment by kgashok** [comment]
Review this [freecodecamp](https://www.freecodecamp.org/news/how-to-use-html-to-open-link-in-new-tab/) article on how to address security concerns when it comes to launching new tabs on link clicks.

**Comment by IMTejesh95** [comment]
I would like to work on this issue. :smile:

**Comment by IMTejesh95** [comment]
file:///home/tejesh/Pictures/Screenshot%20from%202021-12-11%2011-22-51.png
file:///home/tejesh/Pictures/Screenshot%20from%202021-12-11%2011-22-23.png

**Comment by IMTejesh95** [comment]
Attached local screenshots please check!

1. Hover on link to see url in left corner
![Screenshot from 2021-12-11 11-22-51](https://user-images.githubusercontent.com/33658194/145665948-0241debc-88b8-4588-9d6f-803205c6f9dc.jpg)

2. Opened link in new tab
3. 'New issue' opened in new tab after clicking on above link
![Screenshot from 2021-12-11 11-22-23](https://user-images.githubusercontent.com/33658194/145666036-934ff8a2-3ff1-4c55-b76b-a9bbcb555b99.jpg)

**Comment by kgashok** [comment]
@IMTejesh95  - go for it! 

0. Which file are you modifying? 
1. From the above image, the link seems to be in reverse highlighted - how can you avoid this? 
2. Is the link visible in all the pages?

**Comment by IMTejesh95** [comment]
Hey @kgashok,
0. I am modifying `base.htm.j2`. 
2. It's not. :fearful:

**Comment by IMTejesh95** [comment]
Sorry, but I do not understand your point no. 1

**Comment by kgashok** [comment]
Don't bother about Point 1. 
0. Can you correct "an new githbub issue" to "a new github issue"
1. And change 2018, to 2021.

**Comment by kgashok** [comment]
...but this isn't your first Pull Requests, isn't it? I am not sure how you want me to handle this. 
Can you tackle some of the more advanced issues here?

**Comment by IMTejesh95** [comment]
Oh, I made a grammatical mistake there, will fix that right away!
And also change 2018 -> 2021
<hr/>
Yup, this is my first one and I think I can tackle the advanced issues too :smile:

**Comment by IMTejesh95** [comment]
> Don't bother about Point 1.
> 
> 0. Can you correct "an new githbub issue" to "a new github issue"
> 1. And change 2018, to 2021.

Pushed these changes.

**Comment by kgashok** [comment]
Thank you for your contribution, @IMTejesh95
