### ISSUE TITLE
A left side "Github Issue Ribbon" to encourage feedback via issues on the github repo

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#119]
Please review #118  to get the context. A more elegant resolution would be a Left side ribbon with the words "New Issue" that links to the "New Issue" dialog on github.  For inspiration, please see https://github.blog/2008-12-19-github-ribbons/

![image](https://user-images.githubusercontent.com/2399010/145623833-3c7b302a-3832-4cdc-b3cd-31832c52adde.png)

**Comment by qadirpervez** [comment]
I would like to work on this issue.

**Comment by kgashok** [comment]
Can you please elaborate on how you will go about doing this? 
Thanks,

**Comment by Deepthi-Deepu** [comment]
I would like to work on this issue

**Comment by kgashok** [comment]
> I would like to work on this issue

Done, @Deepthi-Deepu !

**Comment by kgashok** [comment]
@Pavithratrdev , @Deepthi-Deepu take a look at the impact on the Mobile Browser, screenshot below. 
The recently introduced left "Feedback" ribbon has pushed the Centre Heading to the right, and getting below the right Github ribbon.

Please fix this. 

![image](https://user-images.githubusercontent.com/2399010/149007509-aa415cc0-23dc-46dd-9902-823a6d8686ec.png)

**Comment by kgashok** [comment]
@Deepthi-Deepu @Pavithratrdev, please set a deadline to fix this.

**Comment by Pavithratrdev** [comment]
> @Deepthi-Deepu @Pavithratrdev, please set a deadline to fix this.

**Comment by Pavithratrdev** [comment]
Sir, Will complete by tomorrow EOD

**Comment by Pavithratrdev** [comment]
@Deepthi-Deepu : Please move the feedback ribbon to right side, below the ribbon "Fork me on github"

**Comment by Deepthi-Deepu** [comment]
I will solve it soon sir.
