### ISSUE TITLE
keyboard shortcut for "Send Note"

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#126]
Need a keyboard shortcut `<Ctrl> + <Enter>` for "Send Note" button. 

![image](https://user-images.githubusercontent.com/2399010/147033672-77919cb3-7bf8-4d0c-9d44-860dc65ac8a4.png)

**Comment by ASHISHKUMAR2411** [comment]
If it is a form then, One thing we know is by default we can submit forms with the enter key, it is not the same when forms have a Textarea tag or contenteditable attribute. For that, we can use jquery to trigger the submit button.
`$('form').keydown(function(event) {
  if (event.ctrlKey && event.keyCode === 13) {
    $(this).trigger('submit');
  }
})`
Ref - [https://harlemsquirrel.github.io/javascript/2017/02/27/submit-forms-ctrl-enter.html](url)

**Comment by kgashok** [comment]
@ASHISHKUMAR2411 do you want to take this issue up?

**Comment by Deepthi-Deepu** [comment]
I would like to work on this

**Comment by kgashok** [comment]
This only works from the Sender Dialog box. And that's okay.
