### ISSUE TITLE
Focus on the Note Editor as soon as the page is loaded

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#130]
After the note editor page is loaded, the focus of the cursor can be placed immediately in the Note Editor dialog. 
This will allow the user to start typing in the message thereafter. 

![image](https://user-images.githubusercontent.com/2399010/147284967-2eb7e159-4ff2-4617-8d52-f4a3b5771b8a.png)

**Comment by siddhantdixit** [comment]
Can I work in this?

**Comment by kgashok** [comment]
Please indicate how you will go about doing this. 
That way, I will be able to accept the PR as soon as you do it.

**Comment by siddhantdixit** [comment]
@kgashok  Thanks for assigning this to me.

https://github.com/BlitzKraft/saythanks.io/blob/3b015fb2bf7030de81d5adf2b1d2de2a43388bf0/saythanks/templates/submit_note.htm.j2#L21

This can be resolved by adding **autofocus** attribute to the corresponding textarea in submit_note template

**Comment by kgashok** [comment]
Good idea, go ahead with your PR, after you've tested it as well.

**Comment by Deepthi-Deepu** [comment]
I can solve this issue

**Comment by kgashok** [comment]
@Deepthi-Deepu , @siddhantdixit  - First-come first-fold! Of course, provided the PR works as expected! 
Good luck!

**Comment by kgashok** [comment]
Works on the local host, but not on the server.

**Comment by siddhantdixit** [comment]
@kgashok I think it should work same on server as localhost as we have only changed some html attributes. 🤔

**Comment by kgashok** [comment]
Yes, @siddhantdixit, it works now. Thanks,
