### ISSUE TITLE
Useless inheritance from `object` PYL-R0205

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#142]
Two lines that need fixing: 

- [Note](https://github.com/BlitzKraft/saythanks.io/blob/9a5655743ea2f67c3661b99869bed0a341be2f51/saythanks/storage.py#L22)
- [Inbox](https://github.com/BlitzKraft/saythanks.io/blob/9a5655743ea2f67c3661b99869bed0a341be2f51/saythanks/storage.py#L86)

**Comment by Professor-Sathish** [comment]
I would like to do , can you assign me sir
