### ISSUE TITLE
Do not use bare `except`, specify exception instead FLK-E722

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#145]
The issue is flagged at this [line](https://github.com/BlitzKraft/saythanks.io/blob/master/saythanks/storage.py#L123-L123) and [here](https://github.com/BlitzKraft/saythanks.io/blob/master/saythanks/storage.py#L142-L142).

Using `except` without a specific [exception](https://docs.python.org/3.6/library/exceptions.html) can be error prone. Possible bug risk as well.

**Comment by Pavithratrdev** [comment]
Sir, Both #145 & #173 are same

**Comment by kgashok** [comment]
Duplicate issue, as reported by @Pavithratrdev 
Closing this.
