### ISSUE TITLE
Found some variables redeclared JS-0085

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#146]
The issue is with this line [here](https://github.com/BlitzKraft/saythanks.io/blob/master/saythanks/static/js/main.js#L16-L16).

In JavaScript, it's possible to redeclare the same variable name using `var`.   
This can lead to confusion as to where the variable is actually declared and initialized.

**Comment by sumit-158** [comment]
can I work on this?

**Comment by kgashok** [comment]
@sumit-158 the issue got closed much earlier. Please picks another one.
