### ISSUE TITLE
Timestamp each note in the inbox

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#157]
It would be good if the time of when the note was sent is also displayed. 
Which means, the note has to be timestamped with the date (as per the time zone).

**Comment by williskneeland** [comment]
I'd like to try adding this!

**Comment by kgashok** [comment]
@williskneeland , all yours.

**Comment by Deepthi-Deepu** [comment]
I would like to work on this

**Comment by williskneeland** [comment]
Feel free to give this to someone else. I'm too busy currently to work on it, apologies.

**Comment by kgashok** [comment]
The title doesn't have to be "timestamp" - it can say `"Date"`, or any other label - what is used in other email systems? 

![image](https://user-images.githubusercontent.com/2399010/150688447-fe967ba7-4fb0-4def-95ce-4ffa8f84e470.png)

**Comment by kgashok** [comment]
@Deepthi-Deepu - incrementally fix each of the above issue. Don't fix everything in one shot and make a PR. Thanks,

**Comment by kgashok** [comment]
and with Verdana, it is three lines: 

![image](https://user-images.githubusercontent.com/2399010/150721729-f0f056fc-b844-4cc0-b35f-0219cf1fd769.png)

**Comment by kgashok** [comment]
![image](https://user-images.githubusercontent.com/2399010/150721879-1cdbd43a-b0d6-4d7a-9dbe-33ced81aa65a.png)

**Comment by Deepthi-Deepu** [comment]
I will make changes and update it soon

**Comment by kgashok** [comment]
Closing this issue for now, @Deepthi-Deepu @Pavithratrdev 

## Super work!
