### ISSUE TITLE
Error on topic feature implementation 

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#160]
@csurfer , 
As per #59 (resolution for #58  ), an error was seen as shown below (see highlighted lines): 

![image](https://user-images.githubusercontent.com/2399010/147857680-0b6051f7-d96c-401e-ba10-eda7f8b32dc9.png)

**Comment by Pavithratrdev** [comment]
Sir, I will fix this

**Comment by kgashok** [comment]
Another error noticed when trying to send note to @arshadkazmi42 saythanks inbox with the topic set to `first-issues`

https://saythanks.io/to/arshadkazmi42/first-issues

![image](https://user-images.githubusercontent.com/2399010/148423635-acde5de0-f18a-4f4f-8c3c-97d7230acc05.png)

**Comment by DeepakChakravarthy** [comment]
@kgashok 

> Another error noticed when trying to send note to @arshadkazmi42 saythanks inbox with the topic set to `first-issues`
> 
> https://saythanks.io/to/arshadkazmi42/first-issues
> 
> ![image](https://user-images.githubusercontent.com/2399010/148423635-acde5de0-f18a-4f4f-8c3c-97d7230acc05.png)


Sir, I will fix this Issue
