### ISSUE TITLE
Keyboard shortcut to Accept the default placeholder contents in the note

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#162]
In conjunction with #159 will provide comprehensive functionality to #59 topic attribution feature that was added. 

> 1. By pressing the right arrow, the placeholder contents can be included as part of the note, and then allow 
user to add some more words...
> 2. Include reference to the topic also in the default placeholder contents, 
> 3. On the mobile, what will be the "touch shortcut" to accept the default placeholder contents?   

> ![image](https://user-images.githubusercontent.com/2399010/147858031-bd4b6993-81a8-4465-9eb9-3445769d5eed.png)

**Comment by tarunkumark** [comment]
I would like to work on this issue, especially the first feature. As for the second feature, while fixing issue #159, #160 @Pavithratrdev and I will push patches for the corresponding features here as well.

**Comment by kgashok** [comment]
Well done, @tarunkumark

**Comment by tarunkumark** [comment]
Thank you sir

**Comment by kgashok** [comment]
The editor acts quite weirdly! Understandably! Again, another case of **inadequate testing** of the new feature! 

After accepting the placeholder code, the "right arrow" key should only move the cursor.  Please fix ASAP! 

![image](https://user-images.githubusercontent.com/2399010/149004251-339d3c0f-d1fc-45b7-936b-1f33266ec20b.png)

@Pavithratrdev @tarunkumark

**Comment by kgashok** [comment]
Probably have to implement the keyboard shortcut as a combination of `<Ctrl> + <Right Arrow>`
