### ISSUE TITLE
Issue in sending email to others after accessing our own inbox

### ISSUE THREAD

**Issue by Pavithratrdev** [BlitzKraft/saythanks.io#177]
Issue in sending email to others after accessing our own inbox.

Link to send message : https://saythanks.io/to/tkksctwo, But email has been received by sender.

![image](https://user-images.githubusercontent.com/63831132/148685789-75161905-17d8-4002-aae6-028b865f9e5c.png)

**Comment by kgashok** [comment]
@Pavithratrdev On a related note, how do we "log out" of our saythanks.io account?

**Comment by kgashok** [comment]
On Google, I can be logged into two accounts at the same time. 
In this case, when I click "Access my saythanks inbox" button, OAuth shows up the options to choose between them.
