### ISSUE TITLE
The Editor should support a Markdown text entry

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#183]
- And a Preview feature when markdown is being used. 
- The note can also have Github recognized emojis?

**Comment by tushar5526** [comment]
For this, it would be more clean and simple if we support markdown and drop all other formats explicitly because markdown supports both standard text and HTML tags. 

The submit_note page should have a Markdown editor with a previewer to write messages in markdown and preview them. The messages should then be parsed and displayed in a custom inbox. 

Please share your thoughts @kgashok @Pavithratrdev

**Comment by tushar5526** [comment]
A markdown editor like this https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic on the submit button page.

**Comment by tushar5526** [comment]
To make it more user friendly we can even use this mode. https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-with-wysiwyg-mode

This will help folks who are do not know markdown syntax

**Comment by Pavithratrdev** [comment]
@tushar5526  : Preview of the Markdown write-up before SUBMIT should be available

**Comment by kgashok** [comment]
Preview feature of the Markdown write-up before SUBMIT should be also be available.

**Comment by tushar5526** [comment]
This mode -> https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic supports for preview feature of the md you write. 

But not everyone is well versed with md tags and it might make the app exclusive to some. Instead I am recommending using this [wysiwyg-mode](https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-with-wysiwyg-mode) on both the submit note side and the inbox section

**Comment by kgashok** [comment]
> But not everyone is well versed with md tags and it might make the app exclusive to some.

That's ok, @tushar5526 - hitherto, saythanks.io was purely plain text based. If people want to get fancy, they can learn MD and use it appropriately. 

I like the https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-with-wysiwyg-mode too. But that can be provided as an option (for those who don't know MD).

**Comment by tushar5526** [comment]
@kgashok I think then I will go ahead with this https://nhn.github.io/tui.editor/latest/tutorial-example01-editor-basic type of theme for the submit note ?

**Comment by kgashok** [comment]
Yes, go ahead @tushar5526

**Comment by kgashok** [comment]
The editor seems to have issues when accessed on the mobile. 
Can you please check @tushar5526 @Pavithratrdev
