### ISSUE TITLE
A better Pip workflow 

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#198]
Please read and implement https://kennethreitz.org/essays/2016/02/25/a-better-pip-workflow 

- Managing a `requirements.txt` file can be problematic, so Pipenv uses the upcoming Pipfile and Pipfile.lock instead, which is superior for basic use cases.

**Comment by tushar5526** [comment]
I am starting with this issue, the only blocker currently I am facing is that many dependencies of this project requires python < 3.6.5 and pipenv has dropped support for python 3.6

I am trying to update dependencies and see if the projects work for 3.7.5

**Comment by tushar5526** [comment]
There is a need to migrate from `records` to `SQLalchemy` for database-related operations. `records` is no more actively maintained and the last commit was 2 years ago. SQLalchemy will also let sayThanks run on python > 3.6

Please, let me know your thoughts @kgashok @Pavithratrdev

**Comment by Pavithratrdev** [comment]
@tushar5526 :We can proceed with SQLalachemy
