### ISSUE TITLE
HTML edited notes are getting email'ed but not saved in database

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#227]
When choosing HTML as the option, 
![image](https://user-images.githubusercontent.com/2399010/174491648-a218a430-ed7b-4582-ae8e-4e4075d7e012.png)

The email arrives alright....

![image](https://user-images.githubusercontent.com/2399010/174491660-a66eebc4-48c6-4171-839c-0c4eae60e647.png)

But it is not getting stored in the inbox database 

![image](https://user-images.githubusercontent.com/2399010/174491682-b790f42f-a188-496a-a0a5-75aef3025a07.png)

**Comment by kgashok** [comment]
@tarunkumark - this is yours to take and close. 
@Pavithratrdev

**Comment by tarunkumark** [comment]
I have actually done this intentionally. If the HTML message contains any Embedded CSS, it will ruin the CSS of the inbox page.

**Comment by kgashok** [comment]
> I have actually done this intentionally. If the HTML message contains any Embedded CSS, it will ruin the CSS of the inbox page.

In that case, don't allow any CSS based notes to be created? Just plain HTML support will do.

**Comment by tarunkumark** [comment]
> > I have actually done this intentionally. If the HTML message contains any Embedded CSS, it will ruin the CSS of the inbox page.
> 
> In that case, don't allow any CSS based notes to be created? Just plain HTML support will do. 

Ok, I will remove the scripts, styles and other related attributes and store the rest in the inbox.

**Comment by kgashok** [comment]
Ok, I will remove the scripts, styles and other related attributes and
store the rest in the inbox.

Super!

  % ashok
