### ISSUE TITLE
The signup process fails - Apparently an issue with the /callback route of the API

### ISSUE THREAD

**Issue by amirbabaei97** [BlitzKraft/saythanks.io#260]
There seems to be an issue with the third-party signup process in the platform. 

To reproduce: 
Sign up on [saythanks.io](https://saythanks.io) using a third-party account(a gmail account):

Output: 
`builtins.KeyError
KeyError: 'nickname'
`

`
File "/root/Desktop/saythanks.io/saythanks/core.py", line 342, in callback_handling
nickname = user_detail_info['nickname']
KeyError: 'nickname'`

**Comment by Pavithratrdev** [comment]
Please check now, it is ressolved
