### ISSUE TITLE
Internal Server Error with GitHub login

### ISSUE THREAD

**Issue by angristan** [BlitzKraft/saythanks.io#46]
Hello!

I get this error while logging in with GitHub to access my inbox.

The url is `https://saythanks.io/callback?code=xxxxx`

**Comment by roniemartinez** [comment]
I got similar issues

**Comment by justalemon** [comment]
Found the same problem while trying to log in with this GitHub account.

I might send a PR. but it appears that the project is no longer updated (because #47 has not been merged, and that was from october of last year).

**Comment by ParthS007** [comment]
@justalemon You can send the PR. We will have a look at it :+1:
