### ISSUE TITLE
Can't login with new account

### ISSUE THREAD

**Issue by patrick-othmer** [BlitzKraft/saythanks.io#53]
Can't login with new account.

Error message: We could not reach the server. Please check your connection and try again.

Possible incorrect 0auth linking?

Request errors:
GET - https://app59226127.auth0.com/user/ssodata - 404
OPTIONS - https://app59226127.auth0.com/usernamepassword/login - 200 - Correct CORS Header

Same Issue already exists, but closed: #52

**Comment by kgashok** [comment]
@patrick-othmer Please note you will have to re-create your inbox again on saythanks.io before you can use it again. After you create a fresh login, the issues should not persist.
