### ISSUE TITLE
[Feature] Adding gitlab auth0 

### ISSUE THREAD

**Issue by BlitzKraft** [BlitzKraft/saythanks.io#57]
Besides email and github, I think gitlab auth is a great option to provide.

**Comment by Pavithratrdev** [comment]
Interesting feature..

**Comment by Pavithratrdev** [comment]
Gitlab integration is secured and it is given only at organization level.
Refer - https://community.auth0.com/t/add-gitlab-as-a-social-connection-for-auth0/44348.
