### ISSUE TITLE
[FeatureRequest] Add attribution to thank you messages

### ISSUE THREAD

**Issue by csurfer** [BlitzKraft/saythanks.io#58]
Developers usually add the SayThanks badge to their Websites and Github projects. Not all messages specify what they are thankful for. If the badges can be created with attribution topics say on the lines of

`saythanks.io/to/<user>/<topic>`

where the topic can be set to project name or website address or whatever, attributing the thanks to a pertinent endpoint becomes easy.

**Comment by kgashok** [comment]
Thanks for the feature suggestion @csurfer
