### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#60]
Is the website down? Or has the service been taken down?

**Comment by BlitzKraft** [comment]
The domain registration has been deactivated. I am trying to find out what happened. Likely, @kennethreitz did it in preparation to transfer, but this is speculation currently.

**Comment by k4m4** [comment]
@kennethreitz any updates about this?

**Comment by jrwrigh** [comment]
Been a couple weeks later. @kennethreitz should I go ahead and remove the url from my repositories?

**Comment by BlitzKraft** [comment]
@jrwrigh I haven't heard back from @kennethreitz regarding this. I have tried contacting via email and github issues. Not sure if that's relevant to you.

**Comment by drupol** [comment]
What is happening it's not working anymore, is the project stopped forever?

**Comment by BlitzKraft** [comment]
I have not been able to get in touch with kenneth reitz. I have requested the domain/hosting to be transferred to me (I'll be bearing the costs too). I have yet to hear from them.

I am looking to get a new domain name for now and keep the application up for now. I am not in favour of that due to this instance having no previous data.

**Comment by angristan** [comment]
It seems the domain name is up for an auction... https://park.io/auctions/view/saythanks.io

**Comment by jrwrigh** [comment]
![text](https://media1.giphy.com/media/4LRkCWLi2MKOc/source.gif)

**Comment by kgashok** [comment]
> It seems the domain name is up for an auction... https://park.io/auctions/view/saythanks.io

**Comment by kgashok** [comment]
I have resurrected the domain and hosted it. Please try now.

**Comment by angristan** [comment]
Awesome! My inbox is empty though, I had a few dozens of messages.

**Comment by BlitzKraft** [comment]
@angristan: It's possible just the domain was resurrected, not the data/hosting. 

@kgashok : is that right?

**Comment by BlitzKraft** [comment]
@kgashok: Thank you for grabbing the domain back and hosting it. 

Could you adjust the scope of the github auth to just need the profile info? I don't think it is wise to request full account access from users for this.

**Comment by ldez** [comment]
The site doesn't seem to work well, I got only 404.

- https://saythanks.io/to/kennethreitz
- https://saythanks.io/to/BlitzKraft
- https://saythanks.io/to/kgashok


The current link created by the site contains email instead of username. (ex: https://saythanks.io/to/example@email.com)

**Comment by BlitzKraft** [comment]
@ldez I am aware of this issue. Working on a fix.

**Comment by ofek** [comment]
@BlitzKraft Hello! Any update?

**Comment by BlitzKraft** [comment]
@ofek The site is up and hosted, thanks to @kgashok. I'm working on bug fixes.

**Comment by ofek** [comment]
Oh yes I meant the old links not working and now use email

**Comment by rugk** [comment]
Your own "say thanks" link is a 4040 link: https://saythanks.io/to/kennethreitz

So there still seems to be something wrong, @kennethreitz42.

Nevertheless thanks for this project and happy [ILoveFS day 2021](https://fsfe.org/activities/ilovefs/)! :hugs:

**Comment by kgashok** [comment]
Project and domain have been resurrected, albeit, in a broken manner. 
@rugk @ofek @angristan
