### ISSUE TITLE
Why does authentication need so much access?

### ISSUE THREAD

**Issue by jrwrigh** [BlitzKraft/saythanks.io#61]
I was signing back up for saythanks after it had been down, but the authentication access that it asks for seems a bit extreme imo:
![image](https://user-images.githubusercontent.com/20801821/73757865-1764cc80-4727-11ea-9d6d-35282d925624.png)

I would imagine all it really needs is the personal info, not all the admin access stuff.

**Comment by BlitzKraft** [comment]
It shouldn't need so much access. I signed up the first time a while ago (before it went down) and don't recall needing this many permissions.

**Comment by BlitzKraft** [comment]
Ignore the closing issue. Clicked the wrong button. My mistake.

**Comment by csurfer** [comment]
+1 @jrwrigh @BlitzKraft: 

Admin access request on 
1. Organization and Teams
2. Public SSH Keys
3. Repository webhooks and services

Deletion of repositories

Access to private and public repositories? 

This is just too much! 

Access user email addresses (read-only) which was the access given earlier is the only one it needs.

**Comment by BlitzKraft** [comment]
@csurfer : yes, I agree. The permissions are wrong. The scope needs to be limited.

**Comment by kgashok** [comment]
The scope has been limited. Please check.

**Comment by BlitzKraft** [comment]
@kgashok: Thank you for the fix.
