### ISSUE TITLE
sqlalchemy.exc.IntegrityError on logging in with Github

### ISSUE THREAD

**Issue by lorrx** [BlitzKraft/saythanks.io#62]
I have changed the primary email address of my Github account. After logging in to saythanks.io the following error was displayed.

`sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "inboxes_pk"
DETAIL:  Key (auth_id)=(github|xxxxxxx) already exists.
 [SQL: 'INSERT into inboxes (slug, auth_id) VALUES (%(slug)s, %(auth_id)s)'] [parameters: {'slug': 'xxxxx@xxxxxxxxx.com', 'auth_id': 'github|xxxxxxxx'}]`

You may not want to publicly report this type of error. How can the account be deleted so that a new registration is possible?

**Comment by Pavithratrdev** [comment]
Sir, I would like to work on this.. 
Reason for error  : "auth_id" column in inboxes table is assigned with "Primary Key" constraint.

Reference link to solve the issue : https://www.youtube.com/watch?v=P-Z1wXFW4Is
