### ISSUE TITLE
Personal email included in the saythanks url

### ISSUE THREAD

**Issue by 0xcrypto** [BlitzKraft/saythanks.io#69]
The reason I want to use saythanks is to avoid direct emails and avoid giving away my personal email. But the email is included in the url itself! What would be the difference if I am giving `https://saythanks.io/to/my@email.com` instead of `my@email.com`?

**Comment by spookyahell** [comment]
I second this - No, i don't hour, minute or day it, I second it :)

**Comment by spookyahell** [comment]
If this issue is not addressed (soon™️), maybe someone should cancel the service/server to avoid paying for something like this

**Comment by PierreAdam** [comment]
Let's not go to calling it useless.... I find the projet really cool to be honest. But I agree that this is an issue as it's clearly showing the email of the owner, including in the message itself. So if you somehow missed it in the URL, it's clearly written in the message now.
If this issue can be resolved, I would definitly use the saythanks.io service.

**Comment by kgashok** [comment]
@PierreAdam by the time I took over maintenance of this repo, that change was already baked in.
My team and I are in the process of resolving this.

**Comment by PierreAdam** [comment]
@kgashok it's really good to know that the project is active and going somewhere ! Wish you well and hopefully soon be able to close this issue ! 😃

**Comment by kgashok** [comment]
@PierreAdam, @0xcrypto, @spookyahell et. al 

This issue has been resolved. Thanks,
