### ISSUE TITLE
configurable font style for note creation form as well as inbox viewing

### ISSUE THREAD

**Issue by kgashok** [BlitzKraft/saythanks.io#77]
The default font now is **HuiFont,** a free Japanese handwriting font. 
![image](https://user-images.githubusercontent.com/2399010/114828482-9489d800-9de7-11eb-81a5-1a988ef0ee20.png)

The user must be able to choose a different font for note creation as well as viewing the inbox.
A "Settings" page might present some choices for the user to choose from.

**Comment by Pavithratrdev** [comment]
Sir, I will work on this

**Comment by kgashok** [comment]
Rope in others as you deem fit - ask them to indicate their interest against this issue.

**Comment by kgashok** [comment]
Actually this might be related to #31  

![image](https://user-images.githubusercontent.com/2399010/147790663-e007b97e-a7fb-4c65-bf2b-67c8155bff6f.png)

**Comment by Pavithratrdev** [comment]
Yes Sir, Both are same - #31 and #77

**Comment by tarunkumark** [comment]
I would like to work on this as well sir

**Comment by kgashok** [comment]
@Pavithratrdev , @tarunkumark 

You can add the screenshots here, to indicate how you intend to go about it. 
Or make it part of the PR request information.

**Comment by kgashok** [comment]
@tarunkumark - if you local development environment works, you should do a PR as well. That way, you will get attribution for the code change.

**Comment by kgashok** [comment]
## For inspiration, here's the Settings page on Memcode 
![image](https://user-images.githubusercontent.com/2399010/148596621-8ce8d213-74da-4b1f-bb6b-9bbaade333e6.png)

**Comment by kgashok** [comment]
@tarunkumark , @Pavithratrdev 
The font change works well. 
However, when reverting back to "Regular" does not bring back the original cursive font. 

![image](https://user-images.githubusercontent.com/2399010/148778122-30cda0f1-3398-43b9-9de5-6afb75312b8f.png)

**Comment by kgashok** [comment]
@tarunkumark @Pavithratrdev, once chosen, it must remember the choice (using [localStorage](https://www.w3schools.com/jsref/prop_win_localstorage.asp)?) as a stop gap measure until you implement the Options page, similar to Memcode.

**Comment by tarunkumark** [comment]
Will look into it sir
